config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'home#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'sign_out', to: 'auth#sign_out'

    resources :bulletins
    resources :categories
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User'

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize: '100x100'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bulletins, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :bulletins, foreign_key: 'creator_id', class_name: 'Bulletin', inverse_of: :creator, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    return unless session[:user_id]

    @user = User.find(session[:user_id])
  end
end

app/controllers/concerns/auth_concern.rb
# frozen_string_literal: true

module AuthConcern
  def sign_in(_user)
    session[:user_id] = user_id
  end

  def sign_out
    session.delete(:user_id)
    session.clear
  end
end

app/controllers/web/auth_controller.rb
class Web::AuthController < ApplicationController
  def callback
    email = auth[:info][:email].downcase
    nickname = auth[:info][:nickname]
    @user = User.find_by(email: email)

    unless  @user
      @user = User.new(email: email, name: nickname)
      @user.save
    end

    session[:user_id] = @user.id
    # redirect_to root_path
    redirect_to root_path, flash: { success: 'Вы успешно вошли!' }
  end

  def sign_out
    session.delete(:user_id)
    session.clear
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/web/bulletins_controller.rb
class Web::BulletinsController < ApplicationController
  before_action :set_bulletin, only: %i[show edit update destroy]

  # GET /bulletins or /bulletins.json
  def index
    @bulletins = Bulletin.all
  end

  # GET /bulletins/1 or /bulletins/1.json
  def show; end

  # GET /bulletins/new
  def new
    @bulletin = Bulletin.new
  end

  # GET /bulletins/1/edit
  def edit; end

  # POST /bulletins or /bulletins.json
  def create
    pp bulletin_params
    @bulletin = current_user.bulletins.build(bulletin_params)
    if @bulletin.save
      redirect_to bulletin_url(@bulletin), notice: 'Bulletin was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /bulletins/1 or /bulletins/1.json
  def update
    respond_to do |format|
      if @bulletin.update(bulletin_params)
        format.html { redirect_to bulletin_url(@bulletin), notice: 'Bulletin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulletin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulletins/1 or /bulletins/1.json
  def destroy
    @bulletin.destroy

    respond_to do |format|
      format.html { redirect_to bulletins_url, notice: 'Bulletin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bulletin
    @bulletin = Bulletin.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bulletin_params
    params.require(:bulletin).permit(:category_id, :creator_id, :title, :description, :image)
  end
end

app/controllers/web/categories_controller.rb
class Web::CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/web/home_controller.rb
class Web::HomeController < ApplicationController
  def index
    @bulletins = Bulletin.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/web/auth_helper.rb
module Web::AuthHelper
end

app/helpers/web/home_helper.rb
module Web::HomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title BulletinBoard
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/shared/nav'
    .container
      = yield

app/views/layouts/shared/_nav.html.slim
.container
  nav.navbar.navbar-expand-lg.navbar-light style=("background-color: #e3f2fd;") 
    .container-fluid
      = link_to t('.brand_name'), root_path, class: 'navbar-brand'
      button.navbar-toggler aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarNavAltMarkup" data-bs-toggle="collapse" type="button" 
        span.navbar-toggler-icon
      #navbarNavAltMarkup.collapse.navbar-collapse
        .navbar-nav
          = link_to t('.home_index'), root_path, class: 'nav-link active'
      ul.nav.nav-pills
        li.nav-item.me-2.d-flex.align-items-center
          - if current_user
            span = current_user.name
            = link_to sign_out_path, :method => 'delete', class: 'nav-link text-dark' do
              span.bi.bi-box-arrow-left data-bs-toggle="tooltip" data-bs-placement="top" title= t('.sign_out')
          - else
            = link_to auth_request_path('github'), :method => 'post', class: 'nav-link text-dark' do
              span.bi.bi-github.me-2
              = t('.sign_in')

app/views/web/bulletins/_form.html.slim
= bootstrap_form_for  @bulletin do |f|
  - if @bulletin.errors.any?
    #error_explanation
      h2 = "#{pluralize(@bulletin.errors.count, 'error')} prohibited this bulletin from being saved:"
      ul
        - @bulletin.errors.full_messages.each do |message|
          li = message

  = f.select(:category_id, Category.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'Please select a category'})
  = f.text_field :title
  = f.text_area :description
  = f.file_field :image
  = f.submit
<% end %>

app/views/web/bulletins/edit.html.slim
h1 Editing bulletin

== render 'form'

=> link_to 'Show', @bulletin
'|
=< link_to 'Back', bulletins_path

app/views/web/bulletins/index.html.slim
h1 Listing bulletins

table
  thead
    tr
      th = t('.сategory')
      th = t('.creator')
      th = t('.title')
      th = t('.description')
      th = t('.image')
      th
      th

  tbody
    - @bulletins.each do |bulletin|
      tr
        td = bulletin.category
        td = bulletin.creator
        td = bulletin.title
        td = bulletin.description
        td = image_tag bulletin.image, class: 'img-thumbnail'
        td = link_to t('show'), bulletin
        td = link_to t('edit'), edit_bulletin_path(bulletin)
        td = link_to t('destroy'), bulletin, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Bulletin', new_bulletin_path

app/views/web/bulletins/new.html.slim
h1 New bulletin

== render 'form'

= link_to 'Back', bulletins_path

app/views/web/bulletins/show.html.slim
p#notice = notice

p
  strong Category:
  = @bulletin.category

p
  strong Creator:
  = @bulletin.creator

p
  strong Title:
  = @bulletin.title

p
  strong Description:
  = @bulletin.description

p
  strong Image:
  = @bulletin.image

=> link_to 'Edit', edit_bulletin_path(@bulletin)
'|
=< link_to 'Back', bulletins_path

app/views/web/categories/_form.html.slim
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, 'error')} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  = bootstrap_form_for(@category) do |f|
    = f.text_field :name
    = f.submit

app/views/web/categories/edit.html.slim
h1 Editing category

== render 'form'

=> link_to 'Show', @category
'|
=< link_to 'Back', categories_path

app/views/web/categories/index.html.slim
h1 Listing categories

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td = link_to 'Show', category
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Category', new_category_path

app/views/web/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/web/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name

=> link_to 'Edit', edit_category_path(@category)
'|
=< link_to 'Back', categories_path

app/views/web/home/index.html.slim
.album.py-5.bg-light
  .container
    .row.row-cols-1.row-cols-sm-2.row-cols-md-3.g-3.mt-3
      - for bulletin in @bulletins
            .col
              .card.shadow-sm
                = image_tag bulletin.image
                .card-body
                  p.card-text
                    = bulletin.title
                  .d-flex.justify-content-between.align-items-center
                    .btn-group
                      = link_to "View", bulletin_path(bulletin), class: 'btn btn-sm btn-outline-secondary'